### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ScottPierce** [bugsnag/bugsnag-source-maps#56]
### Describe the bug
When trying uploading source maps I'm seeing the following error:
```
TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/_work/example/example/node_modules/@bugsnag/source-maps/node_modules/form-data/lib/form_data.js:226:40)
    at FormData._multiPartHeader (/_work/example/example/node_modules/@bugsnag/source-maps/node_modules/form-data/lib/form_data.js:177:33)
    at FormData.append (/_work/example/example/node_modules/@bugsnag/source-maps/node_modules/form-data/lib/form_data.js:70:21)
    at createFormData (/_work/example/example/node_modules/@bugsnag/source-maps/dist/Request.js:47:14)
    at Promise (/_work/example/example/node_modules/@bugsnag/source-maps/dist/Request.js:92:30)
    at new Promise (<anonymous>)
    at /_work/example/example/node_modules/@bugsnag/source-maps/dist/Request.js:91:16
    at Generator.next (<anonymous>)
    at /_work/example/example/node_modules/@bugsnag/source-maps/dist/Request.js:8:71
    at new Promise (<anonymous>)
```

```js
const { browser } = require("@bugsnag/source-maps")

browser
    .uploadMultiple({
        apiKey: apiKey,
        baseUrl: baseUrl,
        directory: dirAbsolutePath,
        overwrite: true,
        appVersion: appVersion,
        logger: logger,
    })
    .catch((error) => {
        console.log(error)
        process.exit(1)
    })
```

### Steps to reproduce
Use the `uploadMultiple` api to try and upload multiple bundles and source maps to bugsnag. It fails with the above exception.

### Environment
* bugsnag-source-maps version: 2.0.0
* Uploading for:
	* [x] Browser
	* [ ] Node
		* Node version:
	* [ ] React Native
		* React Native version:
* Command that was run:

### Example Repo 

```js
const fs = require("fs")
const path = require("path")
const { browser } = require("@bugsnag/source-maps")

const logger = {
    trace: (m) => console.log(m),
    debug: (m) => console.log(m),
    info: (m) => console.log(m),
    success: (m) => console.log(m),
    warn: (m) => console.log(m),
    error: (m) => console.log(m),
    fatal: (m) => console.log(m),
    level: Infinity,
}

let apiKey
let baseUrl
if (process.env.BUILD_CONFIGURATION === "production") {
    console.log("production build detected")
    apiKey = process.env.BUGSNAG_PROD_API_KEY
    baseUrl = "https://example.com"
} else if (process.env.BUILD_CONFIGURATION === "integration") {
    console.log("integration build detected")
    apiKey = process.env.BUGSNAG_INTERNAL_API_KEY
    baseUrl = "https://example.com"
} else {
    throw new Error(
        `Unexpected build configuration: ${process.env.BUILD_CONFIGURATION}`
    )
}

const dirRelativePath = "./firebase/public/example"
if (!fs.existsSync(dirRelativePath")) {
    throw new Error(`'${dirRelativePath}' doesn't exist`)
}
const dirAbsolutePath = path.resolve(dirRelativePath)
console.log(`Trying to upload absolute path ${dirAbsolutePath}`)

// interface UploadMultipleOpts {
//     apiKey: string;
//     baseUrl: string;
//     directory: string;
//     appVersion?: string;
//     overwrite?: boolean;
//     projectRoot?: string;
//     endpoint?: string;
//     detectAppVersion?: boolean;
//     requestOpts?: http.RequestOptions;
//     logger?: Logger;
// }
browser
    .uploadMultiple({
        apiKey: apiKey,
        baseUrl: baseUrl,
        directory: dirAbsolutePath,
        overwrite: true,
        appVersion: process.env.GITHUB_RUN_NUMBER,
        logger: logger,
    })
    .catch((error) => {
        console.log(error)
        process.exit(1)
    })

```

**Comment by xander-jones** [comment]
Discussed via email with @ScottPierce, this is down to an `process.env.BUGSNAG_PROD_API_KEY` being undefined in a GitHub action.
